//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinhKien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LinhKien()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public string MaLK { get; set; }
        public string MaLLK { get; set; }
        public string MaNCC { get; set; }
        public string TenLK { get; set; }
        public string BaoHanh { get; set; }
        public string XuatXu { get; set; }
        public string TinhTrang { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<int> DonGia { get; set; }
        public int SoLuongTon { get; set; }
        public Nullable<int> KhuyenMai { get; set; }
        public string HinhAnh { get; set; }
        public string TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
